"""add workspaces and ai_modules tables

Revision ID: 0d4ca1aa2c17
Revises: ac2e067bb4ea
Create Date: 2025-11-10 21:53:28.702031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d4ca1aa2c17'
down_revision: Union[str, Sequence[str], None] = 'ac2e067bb4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_modules',
    sa.Column('module_type', sa.Enum('RAG', 'N8N_WORKFLOW', 'EMBEDDINGS', 'LLM', 'SEARCH', name='ai_module_type'), nullable=False, comment='Тип модуля (RAG/N8N_WORKFLOW/и т.д.)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название модуля'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание функционала'),
    sa.Column('provider', sa.String(length=100), nullable=False, comment='Провайдер (openrouter/openai)'),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='JSON Schema для валидации конфига'),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Конфигурация по умолчанию'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Доступен ли модуль'),
    sa.Column('version', sa.String(length=50), nullable=True, comment="Версия модуля (например, 'v1.0')"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ai_modules_is_active'), 'ai_modules', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_modules_module_type'), 'ai_modules', ['module_type'], unique=False)
    op.create_index(op.f('ix_ai_modules_provider'), 'ai_modules', ['provider'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название workspace'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Уникальный URL-friendly идентификатор'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание назначения workspace'),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='workspace_visibility', create_constraint=True), nullable=False, comment='Видимость workspace (PUBLIC/PRIVATE)'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='UUID владельца workspace'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='JSONB настройки workspace (валидируется JSON Schema)'),
    sa.Column('ai_modules_enabled', sa.Boolean(), nullable=False, comment='Флаг активации AI модулей (RAG, n8n, search)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_ai_modules_enabled'), 'workspaces', ['ai_modules_enabled'], unique=False)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_index(op.f('ix_workspaces_visibility'), 'workspaces', ['visibility'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='UUID workspace'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID пользователя'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='workspace_member_role', create_constraint=True), nullable=False, comment='Роль в workspace (OWNER/ADMIN/MEMBER)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_role'), 'workspace_members', ['role'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspace_modules',
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='ID workspace'),
    sa.Column('module_id', sa.UUID(), nullable=False, comment='ID AI модуля'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='Включён ли модуль'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Конфигурация модуля для workspace'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Приоритет для ранжирования (выше = важнее)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['ai_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_modules_is_enabled'), 'workspace_modules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_workspace_modules_module_id'), 'workspace_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_workspace_modules_workspace_id'), 'workspace_modules', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_modules_workspace_id'), table_name='workspace_modules')
    op.drop_index(op.f('ix_workspace_modules_module_id'), table_name='workspace_modules')
    op.drop_index(op.f('ix_workspace_modules_is_enabled'), table_name='workspace_modules')
    op.drop_table('workspace_modules')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_role'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_visibility'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_ai_modules_enabled'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_ai_modules_provider'), table_name='ai_modules')
    op.drop_index(op.f('ix_ai_modules_module_type'), table_name='ai_modules')
    op.drop_index(op.f('ix_ai_modules_is_active'), table_name='ai_modules')
    op.drop_table('ai_modules')
    # ### end Alembic commands ###
