"""feat: Add KnowledgeBase, Document and DocumentChunk models with pgvector

Revision ID: 1958dddd6da0
Revises: 0d4ca1aa2c17
Create Date: 2025-11-11 04:13:35.577111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1958dddd6da0'
down_revision: Union[str, Sequence[str], None] = '0d4ca1aa2c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Включаем расширение pgvector
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='UUID workspace, которому принадлежит KB'),
    sa.Column('kb_type', sa.String(length=10), nullable=False, comment='Тип knowledge base (rag/kag)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название knowledge base'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание knowledge base'),
    sa.Column('vector_store_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Конфигурация vector store (dimension, metric, index_type)'),
    sa.Column('documents_count', sa.Integer(), nullable=False, comment='Количество документов в KB'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли knowledge base'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('documents_count >= 0', name='check_documents_count_positive'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_bases_workspace_active', 'knowledge_bases', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_workspace_id'), 'knowledge_bases', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('kb_id', sa.UUID(), nullable=False, comment='UUID knowledge base'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Имя файла документа'),
    sa.Column('file_path', sa.String(length=1000), nullable=True, comment='Путь к файлу в storage'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Размер файла в байтах'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME тип файла'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус обработки документа'),
    sa.Column('chunks_count', sa.Integer(), nullable=False, comment='Количество чанков документа'),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Дополнительные метаданные документа'),
    sa.Column('indexed_at', sa.DateTime(), nullable=True, comment='Дата завершения индексации'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке при обработке'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunks_count >= 0', name='check_chunks_count_positive'),
    sa.CheckConstraint('file_size > 0', name='check_file_size_positive'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.create_index('ix_documents_kb_status', 'documents', ['kb_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False, comment='UUID документа'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Порядковый номер чанка в документе'),
    sa.Column('content', sa.Text(), nullable=False, comment='Текстовое содержимое чанка'),
    sa.Column('embedding', Vector(1536), nullable=False, comment='Vector embedding для RAG поиска (1536 dimensions)'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Количество токенов в чанке'),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Дополнительные метаданные чанка'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='check_chunk_index_positive'),
    sa.CheckConstraint('token_count > 0', name='check_token_count_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document_index', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('ix_documents_kb_status', table_name='documents')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_knowledge_bases_workspace_id'), table_name='knowledge_bases')
    op.drop_index('ix_knowledge_bases_workspace_active', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
