"""add_issue_comments_table

Revision ID: 53e204534cd8
Revises: d8e5325d4bca
Create Date: 2025-11-11 17:56:06.553729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e204534cd8'
down_revision: Union[str, Sequence[str], None] = 'd8e5325d4bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_comments',
    sa.Column('issue_id', sa.UUID(), nullable=False, comment='ID проблемы'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='ID автора комментария'),
    sa.Column('content', sa.Text(), nullable=False, comment='Текстовое содержимое комментария'),
    sa.Column('is_solution', sa.Boolean(), server_default='false', nullable=False, comment='Флаг, отмечающий комментарий как решение проблемы'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_comments_author_id'), 'issue_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_index(op.f('ix_issue_comments_author_id'), table_name='issue_comments')
    op.drop_table('issue_comments')
    # ### end Alembic commands ###
