"""add parent_id to issue_comments for nested threading

Revision ID: 744b26f6a0f4
Revises: 53e204534cd8
Create Date: 2025-11-13 21:39:39.818778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744b26f6a0f4'
down_revision: Union[str, Sequence[str], None] = '53e204534cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_comments', sa.Column('parent_id', sa.UUID(), nullable=True, comment='ID родительского комментария для вложенности'))
    op.create_index(op.f('ix_issue_comments_parent_id'), 'issue_comments', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'issue_comments', 'issue_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue_comments', type_='foreignkey')
    op.drop_index(op.f('ix_issue_comments_parent_id'), table_name='issue_comments')
    op.drop_column('issue_comments', 'parent_id')
    # ### end Alembic commands ###
