"""add_document_services_table

Revision ID: 9acb61d0983f
Revises: d507f80f916c
Create Date: 2025-11-14 12:12:43.088851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9acb61d0983f'
down_revision: Union[str, Sequence[str], None] = 'd507f80f916c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_services',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'spreadsheet', 'text', 'image', name='documentfiletype'), nullable=False),
    sa.Column('cover_type', sa.Enum('generated', 'icon', 'image', name='covertype'), server_default='generated', nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('cover_icon', sa.String(length=100), nullable=True),
    sa.Column('available_functions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_services_author_id'), 'document_services', ['author_id'], unique=False)
    op.create_index(op.f('ix_document_services_file_type'), 'document_services', ['file_type'], unique=False)
    op.create_index(op.f('ix_document_services_is_public'), 'document_services', ['is_public'], unique=False)
    op.create_index(op.f('ix_document_services_title'), 'document_services', ['title'], unique=False)
    op.create_index(op.f('ix_document_services_workspace_id'), 'document_services', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_services_workspace_id'), table_name='document_services')
    op.drop_index(op.f('ix_document_services_title'), table_name='document_services')
    op.drop_index(op.f('ix_document_services_is_public'), table_name='document_services')
    op.drop_index(op.f('ix_document_services_file_type'), table_name='document_services')
    op.drop_index(op.f('ix_document_services_author_id'), table_name='document_services')
    op.drop_table('document_services')
    # ### end Alembic commands ###
