"""add_templates_table

Revision ID: ac2e067bb4ea
Revises: 7c30a71eb1a1
Create Date: 2025-11-10 19:58:50.107003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2e067bb4ea'
down_revision: Union[str, Sequence[str], None] = '7c30a71eb1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название шаблона'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание назначения шаблона'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Категория проблем (hardware, software, process)'),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON структура с определением полей формы'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='Видимость шаблона (public/private/team)'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='UUID создателя шаблона'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Счётчик использований шаблона'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активности шаблона'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_author_id'), 'templates', ['author_id'], unique=False)
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_is_active'), 'templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_templates_title'), 'templates', ['title'], unique=False)
    op.create_index(op.f('ix_templates_visibility'), 'templates', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_visibility'), table_name='templates')
    op.drop_index(op.f('ix_templates_title'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_active'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_index(op.f('ix_templates_author_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
