"""feat: Add N8nWorkflow model for workflow automation

Revision ID: ba18f87e5afd
Revises: 1958dddd6da0
Create Date: 2025-11-11 04:25:55.331516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba18f87e5afd'
down_revision: Union[str, Sequence[str], None] = '1958dddd6da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('n8n_workflows',
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='UUID workspace, которому принадлежит workflow'),
    sa.Column('workflow_name', sa.String(length=200), nullable=False, comment='Название workflow'),
    sa.Column('workflow_type', sa.String(length=50), nullable=False, comment='Тип workflow (auto_categorize/kb_indexing/smart_search/weekly_digest)'),
    sa.Column('n8n_workflow_id', sa.String(length=100), nullable=True, comment='ID workflow в n8n (опционально)'),
    sa.Column('webhook_url', sa.String(length=500), nullable=False, comment='URL webhook для триггера workflow'),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Конфигурация триггера workflow (JSONB)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли workflow'),
    sa.Column('last_triggered_at', sa.String(), nullable=True, comment='Дата последнего запуска workflow'),
    sa.Column('execution_count', sa.Integer(), nullable=False, comment='Количество выполнений workflow'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_n8n_workflows_is_active'), 'n8n_workflows', ['is_active'], unique=False)
    op.create_index(op.f('ix_n8n_workflows_n8n_workflow_id'), 'n8n_workflows', ['n8n_workflow_id'], unique=False)
    op.create_index(op.f('ix_n8n_workflows_workflow_type'), 'n8n_workflows', ['workflow_type'], unique=False)
    op.create_index(op.f('ix_n8n_workflows_workspace_id'), 'n8n_workflows', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_n8n_workflows_workspace_id'), table_name='n8n_workflows')
    op.drop_index(op.f('ix_n8n_workflows_workflow_type'), table_name='n8n_workflows')
    op.drop_index(op.f('ix_n8n_workflows_n8n_workflow_id'), table_name='n8n_workflows')
    op.drop_index(op.f('ix_n8n_workflows_is_active'), table_name='n8n_workflows')
    op.drop_table('n8n_workflows')
    # ### end Alembic commands ###
