"""feat(NORAK-23): обавлено поле template_id и custom_fields в IssueModel

Revision ID: d507f80f916c
Revises: 744b26f6a0f4
Create Date: 2025-11-13 22:46:04.741436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd507f80f916c'
down_revision: Union[str, Sequence[str], None] = '744b26f6a0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('issues', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_issues_template_id'), 'issues', ['template_id'], unique=False)
    op.create_foreign_key(None, 'issues', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_template_id'), table_name='issues')
    op.drop_column('issues', 'custom_fields')
    op.drop_column('issues', 'template_id')
    # ### end Alembic commands ###
